export const GET_LAUNCHES = 'GET_LAUNCHES';
export const GET_LAUNCH = 'GET_LAUNCH';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_LAUNCH_LOADING = 'SET_LAUNCH_LOADING';
export const REMOVE_LAUNCH_LOADING = 'REMOVE_LAUNCH_LOADING';
export const LAUNCH_ERROR = 'LAUNCH_ERROR';
